13 - Authorization/Authorization/SaAuthorizationClaim/Models/Manager/Admin.cs
using SaAuthorizationClaim.Models.Security;

namespace SaAuthorizationClaim.Models.Manager
{
   public class Admin
   {
      public string Name { get; set; }
      public Roles Role { get; set; }
   }
}

13 - Authorization/Authorization/SaAuthorizationClaim/Models/Manager/Manager.cs
namespace SaAuthorizationClaim.Models.Manager
{
   public class Manager
   {
      public string Name { get; set; }
      public bool HasExpenseCredit { get; set; }
   }
}

13 - Authorization/Authorization/SaAuthorizationClaim/Models/Security/LoginInputModel.cs
namespace SaAuthorizationClaim.Models.Security
{
   public class LoginInputModel
   {
      public string Username { get; set; }
      public string Password { get; set; }
      public string RequestPath { get; set; }
      public Roles Role { get; set; }
   }

   public enum Roles
   {
      User,
      Admin
   }
}

13 - Authorization/Authorization/SaAuthorizationClaim/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SaAuthorizationClaim.Controllers
{
   public class HomeController : Controller
   {
      [Authorize]
      public IActionResult Index()
      {
         return View();
      }

      // GET: api/Employee
      [Authorize(Policy = "SystemAdmin")]
      [Route("~/api/GetSystemAdmin")]
      [HttpGet]
      public string GetSystemAdmin()
      {
         return "SystemAdmin";
      }

      [Authorize(Policy = "SiteAdmin")]
      [Route("~/api/GetSiteAdmin")]
      [HttpGet]
      public string GetSiteAdmin()
      {
         return "SiteAdmin";
      }

      // GET: api/Employee
      [Authorize(Policy = "User")]
      [Route("~/api/GetUser")]
      [HttpGet]
      public string GetUser()
      {
         return "User";
      }

      [AllowAnonymous]
      [Route("~/api/GetAll")]
      [HttpGet]
      public string GetAll()
      {
         return "Everybody";
      }
   }
}

13 - Authorization/Authorization/SaAuthorizationClaim/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SaAuthorizationClaim.Models.Manager;
using System.Threading.Tasks;

namespace SaAuthorizationClaim.Controllers
{
   [Authorize(Policy = "Manager")]
   public class ManagerController : Controller
   {
      private readonly IAuthorizationService _authorizationService;

      public ManagerController(IAuthorizationService authorizationService)
      {
         _authorizationService = authorizationService;
      }

      public IActionResult Manager()
      {
         return View();
      }

      [Authorize(Policy = "CanGiveBonus")]
      public IActionResult GiveBonus()
      {
         return View();
      }

      public async Task<IActionResult> PayExpenses(Manager inputModel)
      {
         var result = await _authorizationService.AuthorizeAsync(User, inputModel, "HasExpenseCredit");
         if (!result.Succeeded)
            return Forbid(); 

         return View();
      }
   }
}

13 - Authorization/Authorization/SaAuthorizationClaim/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SaAuthorizationClaim.Models.Security;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SaAuthorizationClaim.Controllers
{
   [AllowAnonymous]
   public class SecurityController : Controller
   {
      public IActionResult Login(string requestPath)
      {
         ViewBag.RequestPath = requestPath ?? "/";
         return View();
      }

      [HttpPost]
      public async Task<IActionResult> Login(LoginInputModel inputModel)
      {
         if (!IsAuthentic(inputModel.Username, inputModel.Password))
            return View();

         HttpContext.Session.SetString("userName", inputModel.Username);
         // Create claims
         var claims = GetClaims(inputModel.Username);

         // Create identity
         ClaimsIdentity identity = new ClaimsIdentity(claims, "cookie");

         // Create principal
         ClaimsPrincipal principal = new ClaimsPrincipal(identity);

         // Sign-in
         await HttpContext.SignInAsync(
                 scheme: "SaSecurityScheme",
                 principal: principal,
                 properties: new AuthenticationProperties
                 {
                    //IsPersistent = true, // for 'remember me' feature
                    //ExpiresUtc = DateTime.UtcNow.AddMinutes(15)
                 });

         //return Redirect(inputModel.RequestPath ?? "/");
         return RedirectToAction("Index", "Home");
      }

      public async Task<IActionResult> Logout(string requestPath)
      {
         await HttpContext.SignOutAsync(
                 scheme: "SaSecurityScheme");

         return RedirectToAction("Login");
      }

      public IActionResult Access()
      {
         return View();
      }

      private bool IsAuthentic(string userName, string password)
      {
         return !string.IsNullOrEmpty(userName);
      }

      private List<Claim> GetClaims(string username)
      {
         if (username.ToLower() == "jim")
         {
            return new List<Claim>
                {
                    new Claim(ClaimTypes.Name, "Sales Manager"),
                    new Claim("Manager", "100"),
                    new Claim("EmployeeId", "10"),
                    new Claim("CanGiveBonus", "100")
                };
         }

         if (username.ToLower() == "bill")
         {
            return new List<Claim>
                {
                    new Claim(ClaimTypes.Name, "Lead Manager"),
                    new Claim("EmployeeId", "11"),
                    new Claim("Manager", "100"),
                    new Claim("HasExpenseCredit", "true")
                };
         }

         if (username.ToLower() == "john")
         {
            return new List<Claim>
                {
                    new Claim(ClaimTypes.Name, "SiteAdmin"),
                    new Claim("EmployeeId", "10"),
                    new Claim("SiteAdmin", "true"),
                    new Claim("UserName","john")
                };
         }

         if (username.ToLower() == "bob")
         {
            return new List<Claim>
                {
                    new Claim(ClaimTypes.Name, "SystemAdmin"),
                    new Claim("SystemAdmin", "true")
                };
         }

         if (username.ToLower() == "joe")
         {
            return new List<Claim>
                {
                    new Claim(ClaimTypes.Name, "User"),
                    new Claim("User", "true"),
                    new Claim(ClaimTypes.DateOfBirth, "01/01/1990")
                };
         }

         return new List<Claim>
            {
                new Claim(ClaimTypes.Name, "Guest")
            };
      }
   }
}

13 - Authorization/Authorization/SaAuthorizationClaim/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Authorization.IAuthorizationService authService
<h2>Manager Portal</h2>
<table>
   <tr>
      <td>Give Bonuses: <a asp-controller="Manager" asp-action="GiveBonus"> Give Bonus</a></td>
   </tr>
   <tr>
      <td>Pay Expenses: <a asp-controller="Manager"
                         asp-action="PayExpenses"
                         asp-route-Name=@Context.Session.GetString("userName")
                         asp-route-HasExpenseCredit="true">Pay Expense</a>
      </td>
   </tr>
</table>
<a asp-controller="Security" asp-action="Logout">Logout</a>

13 - Authorization/Authorization/SaAuthorizationClaim/Views/Manager/GiveBonus.cshtml
<h2>Give Bonus View</h2>

13 - Authorization/Authorization/SaAuthorizationClaim/Views/Manager/Manager.cshtml
<h2>Manager View</h2>

13 - Authorization/Authorization/SaAuthorizationClaim/Views/Manager/PayExpenses.cshtml
<h2>You can PayExpenses - You are manager with Expense Credit</h2>

13 - Authorization/Authorization/SaAuthorizationClaim/Views/Security/Access.cshtml
<p>Access Denied</p>
<a asp-controller="Security" asp-action="Logout">Logout</a>

13 - Authorization/Authorization/SaAuthorizationClaim/Views/Security/Login.cshtml
<form asp-controller="Security" asp-action="Login" method="post">
   <input type="hidden" name="requestPath" id="requestPath" value="@ViewBag.RequestPath" />
   <table >
      <tr>
         <td>User Name</td>
         <td>
            <input type="text" name="userName" id="userName" value="john" />
         </td>
      </tr>
      <tr>
         <td>Password</td>
         <td>
            <input type="password" name="password" id="password" value="hello" />
         </td>
      </tr>
      <tr>
         <td></td>
         <td><input type="submit" value="Login" /></td>
      </tr>
   </table>
</form>
<p>User Names: john, jim (Manager), bill(Lead Manage, CanPayExpenses) </p>